from .registration_page_locators import RegistrationPageLocators
from .common_locators import CommonLocators
from .login_page_locators import LoginPageLocators
from .main_page_locators import MainPageLocators
from .warning_page_locators import WarningPageLocators
